name: flutter_chat_kit_example
description: Demo chat app for flutter_chat_kit.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  cupertino_icons: ^2.0.0
  device_preview: 1.3.1
  flutter:
    sdk: flutter
  flutter_chat_kit:
    path: ../
  flutter_localizations:
    sdk: flutter
  flutter_scale_kit: ^2.0.2
  lemsa_core_kit: ^1.1.0
  slang: ^4.19.2
  slang_flutter: ^4.19.0

dev_dependencies:
  drift: ^2.35.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true
